stages:
    - docker

default:
  tags:
    - k8s

selks:
    stage: docker
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: '/certs'
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    services:
        - docker:24.0.5-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build
            "${CI_PROJECT_DIR}/."
            -f "${CI_PROJECT_DIR}/Dockerfile"
            -t "${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_SHORT_SHA}"
            -t "${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_BRANCH}"
        - docker push ${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_SHORT_SHA}
        - docker push ${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_BRANCH}

tests:
    stage: docker
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: '/certs'
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    services:
        - docker:24.0.5-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build
            "${CI_PROJECT_DIR}/."
            -f "${CI_PROJECT_DIR}/Dockerfile"
            --build-arg "path=/tests"
            -t "${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_SHORT_SHA}"
            -t "${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_BRANCH}"
        - docker push ${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_SHORT_SHA}
        - docker push ${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_BRANCH}


clearndr:
    stage: docker
    image: docker:24.0.5
    variables:
        DOCKER_HOST: tcp://docker:2376
        DOCKER_TLS_CERTDIR: '/certs'
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: '$DOCKER_TLS_CERTDIR/client'
    services:
        - docker:24.0.5-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build
            "${CI_PROJECT_DIR}/."
            -f "${CI_PROJECT_DIR}/Dockerfile"
            --build-arg "path=/clearndr"
            -t "${CI_REGISTRY_IMAGE}/clearndr:${CI_COMMIT_SHORT_SHA}"
            -t "${CI_REGISTRY_IMAGE}/clearndr:${CI_COMMIT_BRANCH}"
        - docker push ${CI_REGISTRY_IMAGE}/clearndr:${CI_COMMIT_SHORT_SHA}
        - docker push ${CI_REGISTRY_IMAGE}/clearndr:${CI_COMMIT_BRANCH}
