stages:
    - docker

default:
  tags:
    - k8s

selks:
    stage: docker
    before_script: []
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ['']
    script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor
            --context "${CI_PROJECT_DIR}/."
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_SHORT_SHA}"
            --destination "${CI_REGISTRY_IMAGE}/selks:${CI_COMMIT_BRANCH}"
            --cache=true
            --cache-copy-layers=true
            --cache-ttl=24h

tests:
    stage: docker
    before_script: []
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ['']
    script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor
            --build-arg "path=/tests"
            --context "${CI_PROJECT_DIR}/."
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_SHORT_SHA}"
            --destination "${CI_REGISTRY_IMAGE}/tests:${CI_COMMIT_BRANCH}"
            --cache=true
            --cache-copy-layers=true
            --cache-ttl=24h

cndr:
    stage: docker
    before_script: []
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: ['']
    script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"$(echo -n $CI_DEPENDENCY_PROXY_SERVER | awk -F[:] '{print $1}')\":{\"auth\":\"$(printf "%s:%s" ${CI_DEPENDENCY_PROXY_USER} "${CI_DEPENDENCY_PROXY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor
            --build-arg "path=/cndr"
            --context "${CI_PROJECT_DIR}/."
            --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
            --destination "${CI_REGISTRY_IMAGE}/cndr:${CI_COMMIT_SHORT_SHA}"
            --destination "${CI_REGISTRY_IMAGE}/cndr:${CI_COMMIT_BRANCH}"
            --cache=true
            --cache-copy-layers=true
            --cache-ttl=24h
